version: "3.1"

services:
  proxy:
    ports:
      - 80:80

  front:
    ports:
      - 8081:80
    volumes:
      - ../../../../labeling-ui:/code:Z

  ############# API SECTION BEGIN #############

  api-nginx:
    ports:
      - 8082:80
    volumes:
      - ../../../../labeling-api/web/AnnoStation:/code

  api-fpm:
    depends_on:
      - api-couchdb
    volumes:
      - ../../../../labeling-api:/code:z

  api-workerpool-low:
    depends_on:
      - api-couchdb
    volumes:
      - ../../../../labeling-api:/code:z

  api-workerpool-normallow:
    depends_on:
      - api-couchdb
    volumes:
      - ../../../../labeling-api:/code:z

  api-workerpool-normal:
    depends_on:
      - api-couchdb
    volumes:
      - ../../../../labeling-api:/code:z

  api-workerpool-high:
    depends_on:
      - api-couchdb
    volumes:
      - ../../../../labeling-api:/code:z

  api-cron:
    depends_on:
      - api-couchdb
    volumes:
      - ../../../../labeling-api:/code:z

  ############# API SECTION END #############


  ############# VIDEO PROCESSING SECTION BEGIN #############

  video-nginx:
    ports:
      - 8090:80

  video-fpm:
    volumes:
      - ../../../../labeling-video-processing:/code:z

  ############# VIDEO PROCESSING SECTION END #############

  ############# DOCUMENTATION SECTION BEGIN #############

  doc-go-swagger:
    volumes:
      - ../../../../labeling-api/doc/swagger:/apiDoc

  ############# DOCUMENTATION SECTION END #############

