annostation_base::authorized_keys: true
php::fpm::pools:
  www:
    listen: 127.0.0.1:9000
    user: www-data

php::fpm::settings:
  PHP/upload_max_filesize: 512M
  PHP/post_max_size: 512M
  PHP/default_socket_timeout: 900

php::extensions:
  mysql: {}

rabbitmq::version: present

supervisord::install_pip: true
supervisord::service_manage: true
supervisord::service_enable: true
supervisord::service_ensure: running

labeling_api::params::config_dir: '/etc/AnnoStation/labeling-api'
labeling_api::params::cache_dir: '/var/cache/labeling_api'
labeling_api::params::database_name: 'labeling_api'
labeling_api::params::database_password: 'pEid4oShu'
labeling_api::params::database_user: 'labeling_api'
labeling_api::params::frame_cdn_dir: '/var/www/frame_cdn'
labeling_api::params::frame_cdn_port: 81
labeling_api::params::frame_cdn_base_url: 'anno.crosscan.com'
labeling_api::params::frame_cdn_allowed_origin: 'http://anno.crosscan.com'
labeling_api::params::frame_cdn_expires: '1d'
labeling_api::params::prepare_test_environment: true
labeling_api::params::secret: 'saddassadasd'
labeling_api::params::user_password: 'xoADo2iMO1okZJIvaQKX'

labeling_api::app::root_dir: '/var/www/labeling-api/current'

labeling_api::mysql::database_name: 'labeling_api'
labeling_api::mysql::database_user: 'labeling_api'
labeling_api::mysql::database_password: 'pEid4oShu'

labeling_api::couch::database_name: 'labeling_api'
labeling_api::couch::prepare_test_environment: true

labeling_api::worker::app_dir: '/var/www/labeling-api/current'
labeling_api::worker::user: www-data

labeling_api::mysql: true
labeling_api::couch: true
labeling_api::worker_queue: true
labeling_api::app: true
labeling_api::run_composer_install: false
