annostation_base::authorized_keys: true
php::fpm::pools:
  www:
    listen: 127.0.0.1:9000
    user: www-data

php::fpm::settings:
  PHP/upload_max_filesize: 512M
  PHP/post_max_size: 512M
  PHP/default_socket_timeout: 900

php::extensions:
  mysql: {}

labeling_api::run_composer_install: false
labeling_api::prepare_test_environment: true
labeling_api::config_dir: '/etc/AnnoStation/labeling-api'
labeling_api::root_dir: '/var/www/labeling-api/current'
labeling_api::cache_dir: '/var/cache/labeling_api'
labeling_api::frame_cdn_dir: '/var/www/frame_cdn'
labeling_api::frame_cdn_hostname: 'anno.crosscan.com'
labeling_api::frame_cdn_allowed_origin: 'http://anno.crosscan.com'
labeling_api::frame_cdn_expires: '1d'
labeling_api::database_host: '127.0.0.1'
labeling_api::database_port: 'null'
labeling_api::database_name: 'labeling_api'
labeling_api::database_user: 'labeling_api'
labeling_api::database_password: 'pEid4oShu'
labeling_api::mailer_transport: 'smtp'
labeling_api::mailer_host: '127.0.0.1'
labeling_api::mailer_user: 'null'
labeling_api::mailer_password: 'null'
labeling_api::secret: 'saddassadasd'
labeling_api::user_password: 'xoADo2iMO1okZJIvaQKX'
