version: "3.5"

services:

  proxy:
    build:
      dockerfile: 'ops/docker/proxy/Dockerfile'
      context: ../../../../
    depends_on:
      - api_nginx
      - front

  rmq:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    restart: always
    healthcheck:
      test: "rabbitmqctl status || exit 1"
      interval: 5s
      timeout: 10s
      retries: 6
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rmq_data:/var/lib/rabbitmq

#  visualizer:
#    image: dockersamples/visualizer:stable
#    ports:
#      - "8888:8080"
##    volumes:
##      - "/var/run/docker.sock:/var/run/docker.sock"
##    deploy:
##      placement:
##        constraints: [node.role == manager]
#

volumes:
  rmq_data:
    driver: local
