version: "3.1"

services:

  proxy:
    build:
      dockerfile: 'ops/docker/proxy/Dockerfile'
      context: ../../../../
    depends_on:
      - api_nginx
#      - front disabled for separate BE and FE build
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.proxy == 1

  rmq:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    restart: on-failure
    healthcheck:
      test: "rabbitmqctl status || exit 1"
      interval: 5s
      timeout: 10s
      retries: 6
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rmq_data:/var/lib/rabbitmq
    deploy:
      placement:
        constraints:
          - node.labels.rmq == 1

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8888:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
  rmq_data:
    driver: local
