annostation_hello_world:
    resource: "@AnnoStationBundle/Controller/"
    type: annotation

api_project_batch_upload:
    resource: "annostation.labeling_api.controller.api.project.batch_upload"
    type: rest

api_project_status:
    resource: "annostation.labeling_api.controller.api.project.status"
    type: rest
    name_prefix: app_api_project_status

api_project_report:
    resource: "annostation.labeling_api.controller.api.project.report"
    type: rest
    name_prefix: app_api_report

api_project_attention:
    resource: "annostation.labeling_api.controller.api.project.attention"
    type: rest
    name_prefix: app_api_project_attention

api_project_export:
    resource: "annostation.labeling_api.controller.api.project.export"
    type: rest
    name_prefix: app_api_project_export_

api_task_labeled_thing_in_frame:
    resource: "annostation.labeling_api.controller.api.task.labeled_thing_in_frame"
    type: rest
    name_prefix: app_api_task_labeled_thing_in_frame_

api_task_labeled_frame:
    resource: "annostation.labeling_api.controller.api.task.labeled_frame"
    type: rest
    name_prefix: app_api_task_labeled_frame_

api_task_export:
    resource: "annostation.labeling_api.controller.api.task.export"
    type: rest
    name_prefix: app_api_task_export_

api_task_labeled_thing:
    resource: "annostation.labeling_api.controller.api.task.labeled_thing"
    type: rest
    name_prefix: app_api_task_labeled_thing_

api_task_interpolate:
    resource: "annostation.labeling_api.controller.api.task.interpolate"
    type: rest
    name_prefix: app_api_task_interpolate_

api_task_timer:
    resource: "annostation.labeling_api.controller.api.task.timer"
    type: rest
    name_prefix: app_api_task_timer_

api_task_status:
    resource: "annostation.labeling_api.controller.api.task.status"
    type: rest
    name_prefix: app_api_task_status_

api_task_user:
    resource: "annostation.labeling_api.controller.api.task.user"
    type: rest
    name_prefix: app_api_task_user_

api_task_attention:
    resource: "annostation.labeling_api.controller.api.task.attention"
    type: rest
    name_prefix: app_api_task_attention

api_task_phase:
    resource: "annostation.labeling_api.controller.api.task.phase"
    type: rest
    name_prefix: app_api_task_phase

api_labeled_thing_in_frame:
    resource: "annostation.labeling_api.controller.api.labeled_thing_in_frame"
    type: rest
    name_prefix: app_api_labeled_thing_in_frame_
