default:
    resource: "AnnoStationBundle\Controller\Index"
    type: annotation

api_project_batch_upload:
    resource: "AnnoStationBundle\Controller\Api\Organisation\\Project\BatchUpload"
    type: annotation

api_project_status:
    resource: "annostation.labeling_api.controller.api.organisation.project.status"
    type: rest
    name_prefix: app_api_organisation_project_status

api_project_report:
    resource: "annostation.labeling_api.controller.api.organisation.project.report"
    type: rest
    name_prefix: app_api_organisation_report

api_project_attention:
    resource: "annostation.labeling_api.controller.api.organisation.project.attention"
    type: rest
    name_prefix: app_api_organisation_project_attention

api_project_export:
    resource: "annostation.labeling_api.controller.api.organisation.project.export"
    type: rest
    name_prefix: app_api_organisation_project_export_

api_task_labeled_thing_in_frame:
    resource: "annostation.labeling_api.controller.api.task.labeled_thing_in_frame"
    type: rest
    name_prefix: app_api_task_labeled_thing_in_frame_

api_task_labeled_thing:
    resource: "annostation.labeling_api.controller.api.task.labeled_thing"
    type: rest
    name_prefix: app_api_task_labeled_thing_

api_task_status:
    resource: "annostation.labeling_api.controller.api.task.status"
    type: rest
    name_prefix: app_api_task_status_

api_task_user:
    resource: "annostation.labeling_api.controller.api.task.user"
    type: rest
    name_prefix: app_api_task_user_

api_task_attention:
    resource: "annostation.labeling_api.controller.api.task.attention"
    type: rest
    name_prefix: app_api_task_attention

api_task_phase:
    resource: "annostation.labeling_api.controller.api.task.phase"
    type: rest
    name_prefix: app_api_task_phase

api_labeled_thing_in_frame:
    resource: "annostation.labeling_api.controller.api.labeled_thing_in_frame"
    type: rest
    name_prefix: app_api_labeled_thing_in_frame_

api_video:
    resource: "annostation.labeling_api.controller.api.video"
    type: rest
    name_prefix: app_api_video_

api_organisation_user:
    resource: "annostation.labeling_api.controller.api.organisation.user"
    type: rest
    name_prefix: app_api_organisation_user_

api_organisation_users:
    resource: "annostation.labeling_api.controller.api.organisation.users"
    type: rest
    name_prefix: app_api_organisation_users_

api_user:
    resource: "annostation.labeling_api.controller.api.user"
    type: rest
    name_prefix: app_api_user_

api_task:
    resource: "annostation.labeling_api.controller.api.task"
    type: rest
    name_prefix: app_api_task_

api_project:
    resource: "annostation.labeling_api.controller.api.organisation.project"
    type: rest
    name_prefix: app_api_organisation_project_

api_test:
    resource: "annostation.labeling_api.controller.api.test"
    type: rest
    name_prefix: app_api_test_

api_status:
    resource: "annostation.labeling_api.controller.api.status"
    type: rest
    name_prefix: app_api_status_

api_current_user:
    resource: "annostation.labeling_api.controller.api.current_user"
    type: rest
    name_prefix: app_api_current_user_

api_organisation_project_count:
    resource: "annostation.labeling_api.controller.api.organisation.project_count"
    type: rest
    name_prefix: app_api_organisation_project_count_

api_task_count:
    resource: "annostation.labeling_api.controller.api.task_count"
    type: rest
    name_prefix: app_api_task_count_

api_labeling_group:
    resource: "annostation.labeling_api.controller.api.organisation.labeling_group"
    type: rest
    name_prefix: app_api_organisation_labeling_group

api_task_configuration:
    resource: "annostation.labeling_api.controller.api.organisation.task_configuration"
    type: rest
    name_prefix: app_api_organisation_task_configuration

api_ui_log:
    resource: "annostation.labeling_api.controller.api.ui_log"
    type: rest
    name_prefix: app_api_ui_log

api_system:
    resource: "annostation.labeling_api.controller.api.system"
    type: rest
    name_prefix: app_api_system

project_importer:
    resource: "annostation.labeling_api.controller.api.organisation.project_importer"
    type: rest
    name_prefix: app_project_importer_

api_organisation:
    resource: "annostation.labeling_api.controller.api.organisation"
    type: rest
    name_prefix: app_api_organisation_

api_organisation_capmaign:
    resource: "annostation.labeling_api.controller.api.organisation.campaign"
    type: rest
    name_prefix: app_api_organisation_campaign_

api_task_replication:
    resource: "annostation.labeling_api.controller.api.task.replication"
    type: rest
    name_prefix: app_api_task_replication_
