# Configure Capistrano to use our own structure
set :deploy_config_path, 'app/capistrano/deploy.rb'
set :stage_config_path, 'app/capistrano/deploy'

# Load DSL and set up stages
require 'capistrano/setup'

# Include default deployment tasks
require 'capistrano/deploy'

# Include copy deployment strategy
require 'capistrano/copy'
