#!/bin/bash
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

if [ -f $(which docker) ]; then
    echo -e "${YELLOW}Starting CouchDB Docker Container${NC}"
    ./scripts/CouchDB/Docker/shutdown.sh
    ./scripts/CouchDB/Docker/start.sh
fi

./bin/phpunit $@

if [ -f $(which docker) ]; then
    echo -e "${YELLOW}Removing CouchDB Docker Container${NC}"
    ./scripts/CouchDB/Docker/shutdown.sh
fi
