labeling_api::mysql: true
labeling_api::couch: false
labeling_api::worker_queue: true
labeling_api::redis: true
labeling_api::app: true
labeling_api::tideways: true

labeling_api::params::create_parameter_files: true
labeling_api::params::database_host: 'mysql'
labeling_api::params::rabbitmq_host: 'workerqueue'
labeling_api::params::couchdb_host: 'couch'
labeling_api::params::couchdb_host_external: 'anno.crosscan.com'
labeling_api::params::couchdb_external_url: 'https://admin:mbifbeB6weHfnPy@anno.crosscan.com/couchdb/'
labeling_api::params::couchdb_port_external: '443'
labeling_api::params::couchdb_path_external: 'couchdb'

tideways::php7: true

php::cli::settings:
  tideways/tideways.api_key: 5E8BP2ucZXkMhXVs
  tideways/tideways.framework: symfony2

php::fpm::settings:
  tideways/tideways.api_key: 5E8BP2ucZXkMhXVs
  tideways/tideways.framework: symfony2
