labeling_api::mysql: false
labeling_api::couch: false
labeling_api::worker_queue: false
labeling_api::redis: true
labeling_api::app: true
labeling_api::tideways: true

labeling_api::params::create_parameter_files: true
labeling_api::params::database_host: 'mysql'
labeling_api::params::couchdb_host: 'couch'
labeling_api::params::rabbitmq_host: 'workerqueue'

tideways::php7: true

php::cli::settings:
  tideways/tideways.api_key: 5E8BP2ucZXkMhXVs
  tideways/tideways.framework: symfony2

php::fpm::settings:
  tideways/tideways.api_key: 5E8BP2ucZXkMhXVs
  tideways/tideways.framework: symfony2
