app:
    resource: "@AppBundle/Resources/config/routing.yml"
    type: rest

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_monitor:
    resource: "@LiipMonitorBundle/Resources/config/routing.xml"
    prefix: /monitor/health