# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
                chain:
                  providers: [annostation.labeling_api.security.user_provider, annostation.labeling_api.security.api_key_user_provider]
        annostation.labeling_api.security.user_provider:
            id : annostation.labeling_api.security.user_provider
        annostation.labeling_api.security.api_key_user_provider:
            id: annostation.labeling_api.security.api_key_user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            entry_point: annostation.labeling_api.authentication_handler
            http_basic:
                realm: "Annostation"
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                default_target_path: /labeling
                always_use_default_target_path: true
                success_handler: annostation.labeling_api.authentication_handler
                failure_handler: annostation.labeling_api.authentication_handler

            logout:       true
            anonymous:    true
            simple_preauth:
                authenticator: annostation.labeling_api.security.apikey_authenticator

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_decision_manager:
        strategy: unanimous

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_SUPER_ADMIN }
        - { path: ^/monitor/, role: ROLE_SUPER_ADMIN }
