<?php

namespace AppBundle\Helper\ProgressIndicator;

use AppBundle\Helper\ProgressIndicator;
use Symfony\Component\Console\Output\OutputInterface;

class ProgressBar extends ProgressIndicator
{
    /**
     * @var OutputInterface
     */
    protected $outputInterface;

    /**
     * @var null|\Symfony\Component\Console\Helper\ProgressBar
     */
    protected $progressBar;

    /**
     * ProgressBar constructor.
     *
     * @param OutputInterface $outputInterface
     */
    public function __construct(OutputInterface $outputInterface)
    {
        parent::__construct();

        $this->outputInterface = $outputInterface;
        $this->progressBar = null;
    }

    public function start($numberOfSteps = 100)
    {
        parent::start($numberOfSteps);
        
        $this->progressBar = new \Symfony\Component\Console\Helper\ProgressBar($this->outputInterface, $numberOfSteps);
    }

    public function finish()
    {
        parent::finish(); // TODO: Change the autogenerated stub
        
        $this->progressBar->finish();
        $this->progressBar = null;
    }

    public function advance($step = 1)
    {
        parent::advance($step); // TODO: Change the autogenerated stub
        
        $this->progressBar->advance($step);
    }
}
