version: "3.1"

services:
  maintenance-composer:
    build:
      dockerfile: 'ops/docker/maintenance/composer/Dockerfile'
      context: ../../../../
    environment:
      - APP_ENV
      - SYMFONY_ENV=${APP_ENV}
      - SYMFONY__COUCHDB__HOST__EXTERNAL=${COUCHDB_HOST_EXTERNAL}
      - SYMFONY__COUCHDB__USER=${COUCHDB_USER}
      - SYMFONY__COUCHDB__PASSWORD=${COUCHDB_PASSWORD}
      - SYMFONY__COUCHDB__USER__READ__ONLY=${COUCHDB_USER_READ_ONLY}
      - SYMFONY__COUCHDB__PASSWORD__READ__ONLY=${COUCHDB_PASSWORD_READ_ONLY}
      - SYMFONY__COUCHDB__EXTERNAL__URL=${COUCHDB_EXTERNAL_URL}
      - SYMFONY__APP__SECRET=${SYMFONY_SECRET}
      - SYMFONY__MAILER__TRANSPORT=${MAILER_TRANSPORT}
      - SYMFONY__MAILER__HOST=${MAILER_HOST}
      - SYMFONY__MAILER__USER=${MAILER_USER}
      - SYMFONY__MAILER__PASSWORD=${MAILER_PASSWORD}
      - SYMFONY__MAILER__FROM=${MAILER_FROM}
      - SYMFONY__S3__BASE__URL=${S3_BASE_URL}
      - SYMFONY__S3__HOST=${S3_HOST}
      - SYMFONY__S3__REGION=${S3_REGION}
      - SYMFONY__S3__KEY=${S3_KEY}
      - SYMFONY__S3__SECRET=${S3_SECRET}
      - SYMFONY__S3__BUCKET__FRAME=${S3_BUCKET_FRAME}
      - SYMFONY__S3__BUCKET__VIDEO=${S3_BUCKET_VIDEO}
      - SYMFONY__CDN__BASE__URL=${CDN_BASE_URL}
      - SYMFONY__RABBITMQ__USER=${RABBITMQ_DEFAULT_USER}
      - SYMFONY__RABBITMQ__PASS=${RABBITMQ_DEFAULT_PASS}
      - SYMFONY__USER__PASSWORD=${USER_PASSWORD}
      #- SYMFONY__MAILER__ENCRYPTION=${MAILER_ENCRYPTION}
      #- SYMFONY__MAILER__AUTH__MODE=${MAILER_AUTH_MODE}
      #- SYMFONY__MAILER__PORT=${MAILER_PORT}
