imports:
  - resource: liip_monitor.yml
  - resource: parameters.yml
  - resource: security.yml
  - resource: customer.yml

parameters:
  redirectAfterLogin: /labeling
  password.policy:
    AtLeastOneSpecialCharacter: true
    AtLeastOneDigit: true
    Length:
      min: 5
      max: 500
    NotBlank: true

doctrine_couch_db: &doctrine_couch_db
    odm:
        document_managers:
            default:
                mappings:
                    AnnoStationBundle:
                        type: annotation
                        is_bundle: true
                        mapping: true
                        prefix: "AnnoStationBundle\\Model"
                        dir: "Model"

oneup_flysystem:
    adapters:
            cache_adapter:
                local:
                    directory: %cache_dir%

    filesystems:
        cache:
            adapter: cache_adapter
            cache: ~
            alias: ~
            mount: ~
        frame_cdn:
            adapter: frame_cdn_dir_adapter
            cache: ~
            alias: ~
            mount: ~
            visibility: public
        video_cdn:
            adapter: video_cdn_dir_adapter
            cache: ~
            alias: ~
            mount: ~
            visibility: private

hagl_worker_pool:
   logger: annostation.labeling_api.vendor.logger
   config: annostation.labeling_api.service.amqp_pool_config
   facade: annostation.labeling_api.vendor.worker_pool.amqp

twig:
  globals:
    fallback.title: AnnoStation
    customer: %customer%

fos_user:
  from_email:
    address: %mailer_from%
    sender_name: no_reply

fos_rest:
    versioning:
        enabled: true

swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    #encryption: "%mailer_encryption%"
    #auth_mode:  "%mailer_auth_mode%"
    #port:       "%mailer_port%"