imports:
  - resource: parameters.yml
  - resource: services.yml
  - resource: security.yml
  - resource: liip_monitor.yml

parameters:
  redirectAfterLogin: /labeling
  pouchdb_feature_enabled: false

doctrine_couch_db: &doctrine_couch_db
    odm:
        document_managers:
            default:
                mappings:
                    AnnoStationBundle:
                        type: annotation
                        is_bundle: true
                        mapping: true
                        prefix: "AnnoStationBundle\\Model"
                        dir: "Model"

oneup_flysystem:
    adapters:
            cache_adapter:
                local:
                    directory: %cache_dir%

    filesystems:
        cache:
            adapter: cache_adapter
            cache: ~
            alias: ~
            mount: ~
        frame_cdn:
            adapter: frame_cdn_dir_adapter
            cache: ~
            alias: ~
            mount: ~
            visibility: public
        video_cdn:
            adapter: video_cdn_dir_adapter
            cache: ~
            alias: ~
            mount: ~
            visibility: private

hagl_worker_pool:
   logger: annostation.labeling_api.vendor.logger
   config: annostation.labeling_api.service.amqp_pool_config
   facade: annostation.labeling_api.vendor.worker_pool.amqp
