liip_monitor:
    checks:
        groups:
            default:
                rabbit_mq:
                    default:
                        host: "%rabbitmq_host%"
                        port: "%rabbitmq_port%"
                        user: "%rabbitmq_user%"
                        password: "%rabbitmq_password%"
                        vhost: "%rabbitmq_vhost%"
                disk_usage:
                    warning:              70
                    critical:             90
                    path:                 '%cache_dir%'
                guzzle_http_service:
                  webserver:
                      url:                  https://localhost
                      headers:              []
                      options:
                          verify: false
                      status_code:          200
                      content:              null
                      method:               GET
                      body:                 null
                  frame_cdn:
                      url:                  %frame_cdn_base_url%
                      headers:              []
                      options:
                          verify: false
                      status_code:          403
                      content:              null
                      method:               GET
                      body:                 null
                  couch_db:
                      url:                  http://%couchdb_host%:%couchdb_port%
                      headers:              []
                      options:              []
                      status_code:          200
                      content:              null
                      method:               GET
                      body:                 null
