_main:
    resource: "../../config/routing.yml"

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /labeling
        permanent: true

annostation:
    resource: "@AnnoStationBundle/Resources/config/routing.yml"
    type: rest

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    type: rest

# redirect to login page if methot is GET (if try to open in browser)
check_login_redirect:
    path: /login_check
    methods: [GET]
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /labeling
        permanent: true
