_main:
    resource: "../../config/routing.yml"

app:
    resource: "@AnnoStationBundle/Resources/config/routing.yml"
    type: rest

# redirect to login page if methot is GET (if try to open in browser)
check_login_redirect:
    path: /login_check
    methods: [GET]
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
        path: /login
        permanent: true
