#!/usr/bin/env node
require('babel-register');

const fs = require('fs');
const program = require('commander');
const CanteenStackRenderer = require('../CanteenStackRenderer').default;

program
  .version('1.0.1')
  .option('-b, --background', 'Background applied before rendering [rgb(0,0,0)]')
  .arguments('<canteen.json> <outputfile>')
  .action(function main(canteenJson, output) {
    const background = program.background || 'rgb(0,0,0)';

    console.log('Parsing ' + canteenJson); // eslint-disable-line no-console
    const stack = JSON.parse(fs.readFileSync(canteenJson, 'utf-8'));

    console.log('Rendering image (' + stack.width + 'x' + stack.height + ').'); // eslint-disable-line no-console
    const renderer = new CanteenStackRenderer(background);
    const canvas = renderer.render(stack);

    console.log('Writing output file: ' + output); // eslint-disable-line no-console
    fs.writeFileSync(output, canvas.toBuffer());

    console.log('All done. Enjoy :)'); // eslint-disable-line no-console
  });

if (process.argv.length < 3) {
  program.help();
}

program.parse(process.argv);


