version: "3.1"

services:
  monitoring-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.2
    hostname: monitoring-elasticsearch
    environment:
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
      xpack.security.enabled: 'false'
      xpack.monitoring.enabled: 'false'
      xpack.graph.enabled: 'false'
      xpack.watcher.enabled: 'false'
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  monitoring-logstash:
    depends_on:
      - monitoring-elasticsearch
    ports:
      - 5044:5044

  monitoring-kibana:
    image: docker.elastic.co/kibana/kibana:5.3.2
    ports:
      - 5601:5601
    depends_on:
      - monitoring-elasticsearch
    environment:
      ELASTICSEARCH_URL: 'http://monitoring-elasticsearch:9200'
      XPACK_SECURITY_ENABLED: 'false'
      XPACK_MONITORING_ENABLED: 'false'

volumes:
  esdata:
    driver: local
