default:
    resource: "AppBundle\Controller\Index"
    type: annotation

api_videoupload:
    resource: "annostation.labeling_api.controller.api.video_upload"
    type: rest
    name_prefix: app_api_videoupload_

api_test:
    resource: "annostation.labeling_api.controller.api.test"
    type: rest
    name_prefix: app_api_test_

