default:
    resource: "AppBundle\Controller\Index"
    type: annotation

api_video:
    resource: "annostation.labeling_api.controller.api.video"
    type: rest
    name_prefix: app_api_video_

api_task:
    resource: "annostation.labeling_api.controller.api.task"
    type: rest
    name_prefix: app_api_task_

api_task_labeled_thing_in_frame:
    resource: "annostation.labeling_api.controller.api.task.labeled_thing_in_frame"
    type: rest
    name_prefix: app_api_task_labeled_thing_in_frame_

api_task_labeled_frame:
    resource: "annostation.labeling_api.controller.api.task.labeled_frame"
    type: rest
    name_prefix: app_api_task_labeled_frame_

api_task_export:
    resource: "annostation.labeling_api.controller.api.task.export"
    type: rest
    name_prefix: app_api_task_export_

api_labeled_thing_in_frame:
    resource: "annostation.labeling_api.controller.api.labeled_thing_in_frame"
    type: rest
    name_prefix: app_api_labeled_thing_in_frame_

api_test:
    resource: "annostation.labeling_api.controller.api.test"
    type: rest
    name_prefix: app_api_test_

api_task_labeled_thing:
    resource: "annostation.labeling_api.controller.api.task.labeled_thing"
    type: rest
    name_prefix: app_api_task_labeled_thing_

api_task_interpolate:
    resource: "annostation.labeling_api.controller.api.task.interpolate"
    type: rest
    name_prefix: app_api_task_interpolate_

api_status:
    resource: "annostation.labeling_api.controller.api.status"
    type: rest
    name_prefix: app_api_status_
