default:
    resource: "AppBundle\Controller\Index"
    type: annotation

api_video:
    resource: "annostation.labeling_api.controller.api.video"
    type: rest
    name_prefix: app_api_video_

api_videoupload:
    resource: "annostation.labeling_api.controller.api.video_upload"
    type: rest
    name_prefix: app_api_videoupload_

api_task:
    resource: "annostation.labeling_api.controller.api.task"
    type: rest
    name_prefix: app_api_task_

api_labeled_thing_in_frame:
    resource: "annostation.labeling_api.controller.api.task.labeled_thing_in_frame"
    type: rest
    name_prefix: app_api_labeled_thing_in_frame_

api_test:
    resource: "annostation.labeling_api.controller.api.test"
    type: rest
    name_prefix: app_api_test_

