version: "3.1"

services:
  front:
    build:
      dockerfile: 'ops/docker/front/Dockerfile'
      context: ../../../../
    deploy:
      restart_policy:
        condition: always
      placement:
        constraints:
          - node.labels.front == 1
