version: "3.5"

services:
  video_nginx:
    build:
      dockerfile: 'ops/docker/video/nginx/Dockerfile'
      context: ../../../../
    depends_on:
        - video_fpm

  video_fpm:
    build:
      dockerfile: 'ops/docker/video/fpm/Dockerfile'
      context: ../../../../
    environment:
      - APP_ENV
      - SYMFONY_ENV=${APP_ENV}
      - S3_BASE_URL
      - S3_HOST
      - S3_KEY
      - S3_SECRET
      - S3_BUCKET_FRAME
      - S3_BUCKET_VIDEO

