version: "3.1"

services:
  video-nginx:
    depends_on:
        - video-fpm

  video-fpm:
    environment:
      - APP_ENV
      - SYMFONY_ENV=${APP_ENV}
      - S3_BASE_URL
      - S3_HOST
      - S3_KEY
      - S3_SECRET
      - S3_BUCKET_FRAME
      - S3_BUCKET_VIDEO
      - STORAGE_TYPE
      - AZURE_BASE_URL
      - AZURE_CMD_EXECUTABLE
      - AZURE_DEFAULT_ENDPOINTS_PROTOCOL
      - AZURE_ACCOUNT_NAME
      - AZURE_CONTAINER
      - AZURE_DIR_VIDEO
      - AZURE_DIR_FRAME
      - AZURE_ACCOUNT_KEY
      - AZURE_BLOB_ENDPOINT
      - XHPROF_DIVIDER
