version: "3.5"

services:
  video_nginx:
    build:
      dockerfile: 'ops/docker/video/nginx/Dockerfile'
      context: ../../../../
    depends_on:
        - video_fpm

  video_fpm:
    build:
      dockerfile: 'ops/docker/video/fpm/Dockerfile'
      context: ../../../../
