version: "3.1"

services:
  proxy:
    command: bash -c '/bin/sed -i "s/api-couchdb/${COUCHDB_HOST}/" /etc/nginx/conf.d/default.conf.tpl && /usr/local/bin/boot.sh'
    # ADD image option like this for pushing image to registry or docker hub
    image: ${REGISTRY_URL}/${COMPANY_NAME}/proxy:${DOCKER_BE_TAG}
    ports:
      - 80:80

  ############# API SECTION BEGIN #############

  api-nginx:
    image: ${REGISTRY_URL}/${COMPANY_NAME}/api_nginx:${DOCKER_BE_TAG}

  api-fpm:
    image: ${REGISTRY_URL}/${COMPANY_NAME}/api_fpm:${DOCKER_BE_TAG}

  api-workerpool-low:
    image: ${REGISTRY_URL}/${COMPANY_NAME}/api_cli:${DOCKER_BE_TAG}

  api-workerpool-normallow:
    image: ${REGISTRY_URL}/${COMPANY_NAME}/api_cli:${DOCKER_BE_TAG}

  api-workerpool-normal:
    image: ${REGISTRY_URL}/${COMPANY_NAME}/api_cli:${DOCKER_BE_TAG}

  api-workerpool-high:
    image: ${REGISTRY_URL}/${COMPANY_NAME}/api_cli:${DOCKER_BE_TAG}

  api-cron:
    image: ${REGISTRY_URL}/${COMPANY_NAME}/api_cron:${DOCKER_BE_TAG}

  ############# API SECTION END #############
